### ISSUE TITLE
documentation for `ASN1ObjectIdentifier` doesn't match actual value

### ISSUE THREAD

**Issue by getify** [oslo-project/asn1#1]
Referring [to this documentation for `ASN1ObjectIdentifier`](https://asn1.oslojs.dev/reference/main/ASN1ObjectIdentifier/), IIUC it asserts the value should have this shape:

```
interface Properties {
	class: [ASN1Class](https://asn1.oslojs.dev/reference/main/ASN1Class);
	type: [ASN1EncodingType](https://asn1.oslojs.dev/reference/main/ASN1EncodingType);
	tag: number;
	value: Uint8Array;
}
```

However, the value I receive for this has a property `encodedId` instead of `value`. Are the docs incorrect, or is this code? Or am I misunderstanding something else?

![Screenshot 2024-06-04 154957](https://github.com/oslo-project/asn1/assets/150330/129ab553-37c8-4ff2-be1a-a9b88f65d630)

----

Side question: for detecting if I find a certain kind of ASN1 value inside the DER, is it better practice to match against the `tag` property (`6` for `ASN1ObjectIdentifier`), or is it more appropriate to use `instanceof` checks?

**Comment by pilcrowonpaper** [comment]
Fixed, thanks! I would use the `instanceof` check to get TS to help you with the typing
