### ISSUE TITLE
Investigating a parsing difference

### ISSUE THREAD

**Issue by getify** [oslo-project/asn1#2]
I've discovered a parsing difference between this library and [another ASN.1 decoding library](https://github.com/yoursunny/asn1.js). I'd like to track down what the difference is. Could be yours is correct, or the other one. Just hoping to get some insight, if you can help.

For convenience, you can get that other library's code to test yourself [from here](https://www.unpkg.com/@yoursunny/asn1@0.0.20200718/dist/asn1.all.min.js). But also, I put together [this codepen to show using their code](https://codepen.io/getify/pen/NWVjmBy), as also illustrated below.

Here's a sample `Uint8Array` (which happens to be a public-key, in SPKI format, as it came back from a webauthn `create()` call):

```js
let publicKeySPKI = new Uint8Array([48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,183,204,74,62,103,183,80,115,18,100,149,100,190,98,42,52,206,9,207,243,57,16,1,3,120,189,206,247,141,35,67,137,141,41,238,131,182,135,153,55,208,36,37,209,34,76,218,79,198,219,46,17,159,14,207,12,126,106,90,202,56,110,238,78,0,217,1,67,131,16,240,136,199,109,17,198,10,157,183,124,150,224,181,170,230,14,230,159,49,244,35,76,117,35,124,102,206,31,96,107,0,70,122,37,216,11,180,35,83,25,194,237,17,66,100,183,110,10,109,85,244,105,83,186,228,145,59,194,249,63,145,26,7,195,117,31,86,45,4,186,26,173,29,203,113,233,252,160,95,105,71,124,64,89,160,172,7,32,24,134,25,178,132,93,54,17,85,9,3,223,255,192,179,190,156,19,29,202,129,69,131,154,209,218,238,11,9,126,18,101,222,67,15,3,191,238,90,229,229,144,95,197,48,220,36,198,16,179,30,101,62,136,241,8,148,124,113,248,143,75,122,64,117,131,51,124,136,34,245,137,135,94,164,112,12,255,162,40,74,139,246,236,200,147,5,95,103,202,227,78,108,121,248,5,59,143,2,3,1,0,1]);
```

Since SPKI is ASN.1 encoded, I of course decode it to get at the actual raw public-key bytes:

```js
// using your library:
let der_1 = ASN1.decodeASN1(publicKeySPKI)[0];

// using @yoursunny/asn1
let der_2 = ASN1.parseVerbose(publicKeySPKI);
```

Then, to get the raw public key from the decoded value:

```js
// using your library:
let pk_1 = der_1.items[1].bytes;

// using @yoursunny/asn1
let pk_2 = der_2.children[1].children[0].children[0].value;
```

The `pk_1` (from your library) is 270 bytes long, whereas the `pk_2` as parsed from the other library is 256 bytes. FWIW, since this is a public key, I was expecting the raw byte length to be 256.

It seems like @yoursunny/asn1 parses and distinguishes the 256 bytes of the public key separately from some other bytes, whereas your parser is returning all 270 bytes together. But I'm not positive about that, just making my best guess.

Do you have any insights into how that other library is parsing the SPKI differently from your library?

**Comment by pilcrowonpaper** [comment]
The public key value in an RSA SPKI public key is ASN.1 encoded, so I think the other library is decoding that too. If you decode the bit string again with `decodeASN1()`, you should get a SEQUENCE with a 256 byte bit string
